### ISSUE TITLE
Raspberry Pi Pico Board RP2040

### ISSUE THREAD

**Issue by Kostya8574** [dr-mod/pico-mpad#2]
Hello, is this 3d model suitable for the Raspberry Pi Pico Board RP2040 TYPE C. And what is the hole in the 3d model bottom for?

**Comment by Kostya8574** [comment]
> Hello, is this 3d model suitable for the Raspberry Pi Pico Board RP2040 TYPE C. And what is the hole in the 3d model bottom for?

**Comment by dr-mod** [comment]
Hi @Kostya8574 , if you want to use type-c you'd have to enlarge the slot for the bigger port. As for the hole at the bottom, it's for an easy access to the BOOTSEL button.

**Comment by Kostya8574** [comment]
> 

Is the boost button on the bottom suitable for a usb type c board?

**Comment by dr-mod** [comment]
I don't have this board so it's hard for me to tell. Based on pictures online it's there and quite close to it's "original" place.

**Comment by Kostya8574** [comment]
Thank you very much
